receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector.railway.internal:4317
      http:
        endpoint: otel-collector.railway.internal:4318

exporters:
  debug:
    verbosity: detailed

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch: {}

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
